vich_uploader:
    db_driver: orm

    mappings:
       upload_image:
           uri_prefix: '%app.path.upload_image%'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
           upload_destination: '%kernel.project_dir%/public%app.path.upload_image%'
